### ISSUE TITLE
Hitting Github API rate limit.

### ISSUE THREAD

**Issue by yanshiyason** [ksivamuthu/aws-copilot-github-action#157]
Hi, Thank you for releasing this library!

I am hitting the rate limit with the GitHub API and I would like to implement authenticated requests to fix the problem.
Here is the output I am seeing:

```
> Run ksivamuthu/aws-copilot-github-action@v0.0.1
> Installing AWS Copilot...
> Error: API rate limit exceeded for 20.172.40.176. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
```

The code which is causing the error is here:

https://github.com/ksivamuthu/aws-copilot-github-action/blob/3ce6a5f868b4aa637a9fc3744f42607be2930ed4/src/main.ts#L68-L71

In the GitHub Actions CI environment, there should be a `GITHUB_TOKEN` environment variable which can be used to make authenticated requests.

https://docs.github.com/en/actions/security-guides/automatic-token-authentication

I will open a PR shortly.

**Comment by ksivamuthu** [comment]
#158

**Comment by ksivamuthu** [comment]
@yanshiyason  Merged and released 0.0.2 release.

**Comment by Axort** [comment]
hey @yanshiyason ! Do I need to do something else in my workflow? I'm sending the github-token param but not sure if that's the right way:

```
on:
  push:
    branches:
      - staging
    paths:
      - "backend/**"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - uses: ksivamuthu/aws-copilot-github-action@v0.0.8
        with:
          command: install
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          copilot --version
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - uses: ksivamuthu/aws-copilot-github-action@v0.0.8
        with:
          command: deploy
          app: myapp
          name: backend
          env: test
          github-token: ${{ secrets.GITHUB_TOKEN }}
```
