### ISSUE TITLE
Add pipeline and/or service name for deploys

### ISSUE THREAD

**Issue by remstone7** [ksivamuthu/aws-copilot-github-action#179]
More of a new feature but the ability to specify a service name for a deploy or the ability to do pipeline deploys would be great!  for a deploy by name it would just take a `name` arg like
```
with:
            command: deploy
            app: app
            env: test
            name: webserver
```
