### ISSUE TITLE
Unable to use deployment action

### ISSUE THREAD

**Issue by qnm** [ksivamuthu/aws-copilot-github-action#180]
Hey,

Thanks for this action, it seems like it could be super useful!

However, using the deploy action leads to an infinite hang as the CLI tool waits for me to choose something!

![image](https://github.com/ksivamuthu/aws-copilot-github-action/assets/5343/efa31e8f-b782-4fec-bb2d-229b4eb41e85)

I've worked around this by running the command directly but I think I must be missing something in how this action is supposed to be used!

Here's how I'm using it:

```
      - uses: ksivamuthu/aws-copilot-github-action@v0.0.4
        with:
          command: deploy
          app: ${{ github.event.repository.name }}
          env: integration
          force: true
```

Any help appreciated!
