### ISSUE TITLE
No ability to use github env vars in manifest

### ISSUE THREAD

**Issue by chlorophant** [ksivamuthu/aws-copilot-github-action#217]
As far as I can tell there is no way to use a github env var or secret inside the copilot manifest using this action.

This functionality is supported by copilot when using it directly.

Example manifest.yml:
```yml
image:
 build: Dockerfile
  port: 8080
  args:
    GIT_SSH_PRIVATE_KEY: ${env.GIT_SSH_PRIVATE_KEY}
```

This is essential for many use cases
